name: main
on:
  push:
    branches:
      - trunk

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - id: echo-hello
        name: Say hello
        run: echo "Hello, world!"
